import Head from "next/head"

export default function Header() {
	return(
		<Head>
			<title>I like burgers</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@300;400;700&display=swap" rel="stylesheet" />
		</Head>
	)
}
